# -*- coding: utf-8 -*-
"""PYTHON_BTTL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4RqghKMICflaV1ZkNeNxk7-ClaPTIq2
"""

# Bai 1: Chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b

a = float(input("Nhap a: "))
b = float(input("Nhap b: "))

print("Tong:", a + b )
print("Hieu:", a - b )
print("Tich:", a * b )

if b != 0:
  print("Thuong:", a / b )
else:
  print("Khong the chia cho 0")

# Bai 2: Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi “Hello World”.

s = "Hello World"
print(s[2:5])

# Bai 3: Xóa khoảng trắng thừa ở đầu và cuối chuỗi “ Hello World ”. Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J.

s = "Hello World"
# Xoa khoang trang
s = s.strip()
# In hoa va in thuong
print("In hoa:", s.upper())
print("In thuong:", s.lower())
# Thay H thanh J
s = s.replace("H", "J")
print("Sau thay:", s)

# Bai 4: In ra “Hello World!” nếu a lớn hơn b.

if a > b:
  print("Hello Wordl!")

# Bai 5: In ra “Yes” nếu a bằng b, ngược lại in “No”.

if a == b:
  print("Yes")
else:
  print("No")

# Bai 6: In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.

if a == b:
  print(1)
elif a > b:
  print(2)
else:
  print(3)

# Bai 7: In ra “Hello World!” nếu a bằng b và b bằng d.

d = float(input("Nhap d: "))

if a == b and b == d:
  print("Hello World!")

# Bai 8: In ra “Hello World!” nếu a bằng b hoặc c bằng d.

c = float(input("Nhap c: "))

if a == b or c == d:
  print("Hello World!")

# Bai 9:  Viet if else 1 dòng

print("Yes") if a > b else print("No")

# Bài 10: Nhập vào 2 số a, b. Thực hiện câu lệnh và cho biết kết quả

print("A") if a < b else print("=") if a == b else print("B")

# Bài 11: Tạo mảng số nguyên a với n phần tử và mảng b chỉ chứa các phần tử chẵn của a.

n = int(input("Nhập số phần tử: "))
a = []

for i in range(n):
    x = int(input(f"a[{i}]: "))
    a.append(x)

b = [x for x in a if x % 2 == 0]

print("Mảng a: ",a)
print("Mảng b: ", b)

# Bài 12: Viết chương trình tính tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5.

tong = sum(i for i in range(1000) if i % 3 == 0 or i % 5 == 0)
print("Tong: ", tong)

# Bài 13: Viết hàm trộn 2 mảng một chiều thành 1 mảng một chiều với mỗi phần tử của mảng mới là tổng của 2 phần tương ứng từ 2 mảng cho trước. Trong quá trình trộn 2 mảng nếu mảng nào còn phần tử thì các phần tử còn lại của mảng đó sẽ đưa vào mảng mới

a = [2, 4, 8]
b = [5, 3, 9, 7]

c = []
min_len = min(len(a), len(b))

for i in range(min_len):
    c.append(a[i] + b[i])

c.extend(a[min_len:])
c.extend(b[min_len:])

print("Mảng mới:", c)

# Bài 14: Cho mảng 2 chiều a có m dòng, n cột chứa số nguyên, viết các hàm sau

# a) Tạo mảng a chứa các số nguyên ngẫu nhiên.
import random

def tao_mang(m, n):
  a = []
  for i in range(m):
      row = []
      for j in range(n):
          row.append(random.randim(1, 10))
      a.append(row)
  return a

# b) Xuất các phần tử thuộc dòng k.
def xuat_mang(a):
  for row in a:
    print(*row)

def xuat_dong(a, k):
  if k < len(a):
    print("Dòng", k, ":", a[k])
  else:
    print("Không có dòng", k)
k = int(input("Nhập dòng k: "))
xuat_dong(a, k)

# c) Xuất các phần tử thuộc cột k.
def xuat_cot(a, k):
  if 0 <= k < len(a[0]):
    print("Cột", k, ":", a[k])
  else:
    print("Không có cột", k)
k = int(input("Nhập cột k: "))
xuat_cot(a, k)

# d) Tìm dòng có tổng lớn nhất nhất 45.
def dong_max_duoi_45(a):
    max_sum = -1
    index = -1

    for i in range(len(a)):
        s = sum(a[i])
        if s < 45 and s > max_sum:
            max_sum = s
            index = i

    return index, max_sum

# e) Tìm cột có tích nhỏ nhất.
def cot_tich_nho_nhat(a):
    n = len(a[0])
    min_tich = float('inf')
    index = -1

    for j in range(n):
        tich = 1
        for i in range(len(a)):
            tich *= a[i][j]
        if tich < min_tich:
            min_tich = tich
            index = j

    return index, min_tich

# f) Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.
def dong_chan_cot_le(a):
    print("Phần tử (dòng chẵn, cột lẻ):")
    for i in range(0, len(a), 2):      # dòng chẵn
        for j in range(1, len(a[0]), 2):  # cột lẻ
            print(a[i][j], end=" ")
    print()

# g) Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.
def tbc_chan_dong_le(a):
    s = 0
    count = 0

    for i in range(1, len(a), 2):   # dòng lẻ
        for x in a[i]:
            if x % 2 == 0:
                s += x
                count += 1

    return s / count if count != 0 else 0

# h) Tính trung bình cộng các phần tử thuộc biên.
def tbc_bien(a):
    m = len(a)
    n = len(a[0])
    s = 0
    count = 0

    for i in range(m):
        for j in range(n):
            if i == 0 or i == m-1 or j == 0 or j == n-1:
                s += a[i][j]
                count += 1

    return s / count

# i) Tính trung bình tích các phần tử không thuộc biên.
def tbc_tich_trong(a):
    m = len(a)
    n = len(a[0])

    tich = 1
    count = 0

    for i in range(1, m-1):
        for j in range(1, n-1):
            tich *= a[i][j]
            count += 1

    return tich / count if count != 0 else 0

# Bài 15: Một sinh viên gồm các thông tin sau:

# a)	Xây dựng cấu trúc SINHVIEN mô tả một sinh viên
class SinhVien:
    def __init__(self, ma, ten, nam_sinh, diem):
        self.ma = ma
        self.ten = ten
        self.nam_sinh = nam_sinh
        self.diem = diem

# b)	Cho một mảng có n sinh viên.
def nhap_ds(n):
    ds = []
    for i in range(n):
        print(f"\nNhập sinh viên {i+1}:")

        ma = input("Mã SV: ")
        ten = input("Tên: ")
        nam = int(input("Năm sinh: "))
        diem = float(input("Điểm TB: "))

        ds.append(SinhVien(ma, ten, nam, diem))

    return ds

# Hàm xuất danh sách
def xuat_ds(ds):
    for sv in ds:
        print(sv.ma, "-", sv.ten, "-", sv.nam_sinh, "-", sv.diem)

# c)	Viết hàm cho biết có bao sinh viên đủ điều kiện lên lớp, biết rằng sinh viên đủ điều kiện lên lớp khi điểm trung bình lớn hơn hoặc bằng 5.
def dem_len_lop(ds):
    count = 0
    for sv in ds:
        if sv.diem >= 5:
            count += 1
    return count

# d)	Xuất các sinh viên đủ 20 tuổi.
from datetime import datetime

def sv_20_tuoi(ds):
    nam_ht = datetime.now().year

    print("\nSinh viên đủ 20 tuổi:")
    for sv in ds:
        if nam_ht - sv.nam_sinh == 20:
            print(sv.ma, sv.ten)

# e)	Đếm số sinh viên học hệ đại học, biết rằng sinh viên hệ DH có mã sinh viên chứa 2 ký tự DH ở vị trí 2,3 trong chuỗi.
def dem_he_dh(ds):
    count = 0
    for sv in ds:
        if len(sv.ma) >= 4 and sv.ma[2:4] == "DH":
            count += 1
    return count

# f)	Cho biết trong mảng có bao nhiêu sinh viên có tên «Lan»
def dem_ten_lan(ds):
    count = 0
    for sv in ds:
        if "Lan" in sv.ten:
            count += 1
    return count

# g)	Cho biết trong mảng có bao nhiêu sinh viên có họ «Phan»
def dem_ho_phan(ds):
    count = 0
    for sv in ds:
        if sv.ten.startswith("Phan"):
            count += 1
    return count

n = int(input("Nhập số sinh viên: "))

ds = nhap_ds(n)

print("\nDanh sách sinh viên:")
xuat_ds(ds)

print("\nSố SV đủ điều kiện lên lớp:", dem_len_lop(ds))

sv_20_tuoi(ds)

print("\nSố SV hệ DH:", dem_he_dh(ds))

print("Số SV tên Lan:", dem_ten_lan(ds))

print("Số SV họ Phan:", dem_ho_phan(ds))